### ISSUE TITLE
[Feature] Generate mypy stubs for google-generativeai package

### ISSUE THREAD

**Issue by thechopkins** [google/generative-ai-python#264]
### Description of the feature request:

To support mypy type checking, please add support for mypy stubs library. 

Example error message:
```
error: Skipping analyzing "google.generativeai.types.safety_types": module is installed, but missing library stubs or py.typed marker  [import-untyped]
note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```

### What problem are you trying to solve with this feature?

Enable mypy support for the project.

**Comment by randomsamples** [comment]
Yes please

**Comment by tsuga** [comment]
Yes, this will be much appreciated!

**Comment by RayyanNafees** [comment]
yes please

**Comment by jyyogi** [comment]
bump!

**Comment by nguaman** [comment]
Any news?

**Comment by colin-kerkhof** [comment]
For other people that find this thread:

adding the following lines to your `pyproject.toml` will solve (most of) your issues:

```toml
[[tool.mypy.overrides]]
module = ["google.genai.*"]
follow_untyped_imports = true
```

**Comment by jackbravo** [comment]
or also

```toml
[[tool.pyright.overrides]]
module = ["google.genai.*"]
follow_untyped_imports = true
```

for pyright :-p
